services:
  event-forwarder:
    build:
      context: .
      args:
        - BUILD_IMAGE=${BUILD_IMAGE}
    ports:
      - 9000:9000
    environment:
      - OPA_URL=http://opa:8181
      - HTTP_LISTEN=:9000
      - TLS_CERT_FILE=tls.crt
      - TLS_KEY_FILE=tls.key
    env_file:
      - "./.env"
    volumes:
      - ./tls.key:/home/nonroot/tls.key:ro
      - ./tls.crt:/home/nonroot/tls.crt:ro
  opa:
    image: openpolicyagent/opa:latest-debug
    command: 
      - run
      - --server
      - --log-level=debug
      - --disable-telemetry
      - --shutdown-grace-period=0
      - --watch
      - --bundle
      - /policy
    ports:
      - 8181:8181
    volumes:
      - ./policy:/policy:ro